### ISSUE TITLE
Carte Shadow

### ISSUE THREAD

**Issue by Planger45** [WildCodeSchool/2022-09-php-orleans-project-papys45#237]
Carte parcours avec shadow, dépassement du background
![Capture d’écran du 2022-11-22 16-29-43](https://user-images.githubusercontent.com/109434733/203354319-375955a8-727a-4bd1-8867-efdc712db890.png)

**Comment by shvilaine** [comment]
Déjà prévu dans une PR qui n'avait pas été validée ce midi
