### ISSUE TITLE
Boutons CRUD

### ISSUE THREAD

**Issue by DrissB45** [WildCodeSchool/2022-09-php-orleans-project-papys45#249]
- Jaune sur du gris peu lisible (surtout pour un papy)
- Majuscule à "Supprimer"
![Capture d’écran du 2022-11-22 16-25-27](https://user-images.githubusercontent.com/109434733/203353475-21df9e90-22fd-4907-b5af-898c8e8b2084.png)

**Comment by shvilaine** [comment]
Modified the color to blue + OK caps
